### ISSUE TITLE
Issues with RNAfold 

### ISSUE THREAD

**Issue by aemoor** [hanfang/scikit-ribo#2]
I got stuck with creating the RNAfold input file.Both call_rnafold.py and process_rnafold.py are not added to the path by setup and the documentation is not clear regarding the parameters of this function. Is RNAfold a dependency of scikit-ribo? Thanks for clarifying

**Comment by aemoor** [comment]
I'm trying to manually run gtf_preprocess.py to get expandCDS.fasta which is a required input for call_rnafold.py (since its output is required for scikit-ribo-build.py, let me know if I misunderstood this).

gtf_process run on a freshly downloaded GTF and fasta DNA from Ensembl results in this reproducible error:

Traceback (most recent call last):
  File "/miniconda3/bin/gtf_preprocess.py", line 268, in <module>
    worker.convertGtf()
  File "/miniconda3/bin/gtf_preprocess.py", line 55, in convertGtf
    geneBed12 = self.db.bed12(geneName, name_field='gene_id')
  File "/Users/andreas/miniconda3/lib/python3.6/site-packages/gffutils/interface.py", line 1192, in bed12
    % (last, feature.stop))
ValueError: End of last exon (91950640) does not match end of feature (91950725)

It would be great if you could clarify these preprocessing steps that include RNAfold and/or provide a prebuilt RNAfold file for mouse (ftp://ftp.ensembl.org/pub/release-84/gtf/mus_musculus) like the currently offered E.coli and yeast version.
Thanks a lot

**Comment by hanfang** [comment]
Hi Andreas, 

1) I am still thinking about whether to include `call_rnafold.py` as part of the executables.  

2) RNAfold is not a dependency for `Scikit-ribo` but is needed for running `call_rnafold.py`.

3) I recently ran into a similar issue like yours. The reason is that `gffutils` was trying to validate the gtf file that you provided. As you can tell from the error message, it does contain invalid entries even though it is a *fresh* gtf file. Do you think you can find a valid gtf file for mouse from elsewhere? It is frustrating that the one from Ensembl has such errors.

4) That being said, can you hold off on running `Scikit-ribo` on your mouse data? I want to spend some time on figuring out the best option when dealing with such errors. 

5) Have you successfully run it on E.coli and yeast data? I have users reported that it was okay for them. Thanks.

Han
